version: "3.9"

services:
  sqlserver:
    container_name: change-mgmt-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd123!"
    ports:
      - "1433:1433"
     volumes:
      - sql_data:/var/opt/mssql   # ðŸ”¥ PERSIST DATA    
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd123!' -C -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
        sql_data:
        
  api:
    build:
      context: ./backend/ChangeManagement.Api
    container_name: change-mgmt-api
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=ChangeManagementDB;User Id=sa;Password=P@ssw0rd123!;TrustServerCertificate=True"
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  web:
    build:
      context: ./frontend
    container_name: change-mgmt-web
    ports:
      - "5173:5173"
    depends_on:
      - api
